spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/votacao_db
    username: postgres
    password: 7654321
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate   # Flyway controla o schema, não o Hibernate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

logging:
  level:
    com.votacao: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.security: DEBUG

jwt:
  secret: 5f3a8c9b2e1d4f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a
  expiration-ms: 3600000 # 1 hora